<?php

class EstadisticaDAO extends BaseDAO
{
    private $nombreTabla = "estadistica";

    public function __construct()
    {
        parent::__construct($this->nombreTabla);
    }

    function view($id)
    {
        return parent::view($id); // TODO: Change the autogenerated stub
    }

    function list()
    {
        return parent::list();
    }

    function delete($id)
    {
        parent::delete($id); // TODO: Change the autogenerated stub
    }

    function edit($id, object $objeto)
    {
        try {
            $stm = $this->conexion->prepare("UPDATE `estadistica` set `idJugador`=?, `nombreEquipo`=?, `nombreLiga`=?, `PPP`=?, `APP`=?, `RPP`=?, `porcentajeDobles`=?, `porcentajeTriples`=?, `MIN`=?, `porcentajeTL`=?, `ROB`=?, `TAP`=?, `temporada`=? where idEstadistica=?");
            $stm->execute(array(
                $objeto->getIdJugador(),
                $objeto->getNombreEquipo(),
                $objeto->getNombreLiga(),
                $objeto->getPPP(),
                $objeto->getAPP(),
                $objeto->getRPP(),
                $objeto->getPorcentajeDobles(),
                $objeto->getPorcentajeTriples(),
                $objeto->getMIN(),
                $objeto->getPorcentajeTL(),
                $objeto->getROB(),
                $objeto->getTAP(),
                $objeto->getTemporada(),
                $id
            ));
        } catch (Exception $e) {
            die($e->getMessage());
        }
    }

    function add(object $objeto)
    {
        try {
            $stm = $this->conexion->prepare("INSERT INTO `estadistica`(`idJugador`, `nombreEquipo`, `nombreLiga`, `PPP`, `APP`, `RPP`, `porcentajeDobles`, `porcentajeTriples`, `MIN`, `porcentajeTL`, `ROB`, `TAP`, `temporada`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)");
            $stm->execute(array(
                $objeto->getIdJugador(),
                $objeto->getNombreEquipo(),
                $objeto->getNombreLiga(),
                $objeto->getPPP(),
                $objeto->getAPP(),
                $objeto->getRPP(),
                $objeto->getPorcentajeDobles(),
                $objeto->getPorcentajeTriples(),
                $objeto->getMIN(),
                $objeto->getPorcentajeTL(),
                $objeto->getROB(),
                $objeto->getTAP(),
                $objeto->getTemporada()
            ));
        } catch (Exception $e) {
            die($e->getMessage());
        }
    }

    public function getJugadoresWithEstadistica($id)
    {
        try {
            $result = null;
            $stm = $this->conexion->prepare("SELECT * FROM estadistica where idJugador=?;");
            $stm->execute(array($id));
            if ($stm->rowCount() != 0) {
                $result = $stm->fetchAll(PDO::FETCH_CLASS, "Estadistica");
            }
            return $result;
        } catch (Exception $e) {
            die($e->getMessage());
        }
    }
}