<?php

/**
 * Class VideoDAO
 * @author Sandra <a href="mailto:sandraguerreror1995@gmail.com>sandraguerreror1995@gmail.com</a>
 */
class VideoDAO extends BaseDAO
{
    /**
     * @var string
     */
    private $nombreTabla = "video";

    /**
     * VideoDAO constructor.
     */
    public function __construct()
    {
        parent::__construct($this->nombreTabla);
    }

    /**
     * Function view
     * @param $id
     * @return mixed|null
     */
    function view($id)
    {
        return parent::view($id); // TODO: Change the autogenerated stub
    }

    /**
     * Function list
     * @return array|null
     */
    function list()
    {
        return parent::list(); // TODO: Change the autogenerated stub
    }

    /**
     * Function delete
     * @param object $id
     * @return mixed|void
     */
    function delete($id)
    {
        parent::delete($id); // TODO: Change the autogenerated stub
    }

    /**
     * Function edit
     * @param $id
     * @param object $objeto
     * @return mixed|void
     */
    function edit($id, object $objeto)
    {
        $stm = $this->conexion->prepare("UPDATE `video` set `idJugador`=?, `tipoVideo`=?, `isPublico`=?, `ruta`=? where idVideo=?");
        $stm->execute(array(
            $objeto->getIdJugador(),
            $objeto->getTipoVideo(),
            $objeto->getIsPublico(),
            $objeto->getRuta(),
            $id
        ));
    }

    /**
     * Function add
     * @param object $objeto
     * @return mixed|void
     */
    function add(object $objeto)
    {
        $stm = $this->conexion->prepare("INSERT INTO `video`(`idJugador`, `tipoVideo`, `isPublico`, `ruta`) VALUES (?,?,?,?)");
        $stm->execute(array(
            $objeto->getIdJugador(),
            $objeto->getTipoVideo(),
            $objeto->getIsPublico(),
            $objeto->getRuta()
        ));
    }

    /**
     * Function getHighlightsFromJugador
     * @param $id
     * @return array|null
     */
    public function getHighlightsFromJugador($id)
    {
        try {
            $result = null;
            $stm = $this->conexion->prepare('SELECT * FROM `video` WHERE idJugador=? and video.tipoVideo="highlight";');
            $stm->execute(array($id));
            if ($stm->rowCount() != 0) {
                $result = $stm->fetchAll(PDO::FETCH_CLASS, "Video");
            }
            return $result;
        } catch (Exception $e) {
            die($e->getMessage());
        }
    }

    /**
     * Function getPartidosCompletosFromJugador
     * @param $id
     * @return array|null
     */
    public function getPartidosCompletosFromJugador($id)
    {
        try {
            $result = null;
            $stm = $this->conexion->prepare('SELECT * FROM `video` WHERE idJugador=? and video.tipoVideo="partido";');
            $stm->execute(array($id));
            if ($stm->rowCount() != 0) {
                $result = $stm->fetchAll(PDO::FETCH_CLASS, "Video");
            }
            return $result;
        } catch (Exception $e) {
            die($e->getMessage());
        }
    }

}